language: python
python:
 - 2.6
 - 2.7
 - 3.3
 - 3.4
script: nosetests
install:
 - sudo apt-get install librtmp0 librtmp-dev libffi-dev
 - pip install "cffi>=0.6,<1.0"
 - pip install --no-use-wheel .
